apiVersion: apps/v1
kind: Deployment
metadata:
  name: rat-or-cat-frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: rat-or-cat/frontend
          ports:
            - containerPort: 4200
