apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-images-nest-rest
  namespace: rat-or-cat
spec:
  selector:
    matchLabels:
      app: service-images-nest-rest
  template:
    metadata:
      labels:
        app: service-images-nest-rest
    spec:
      containers:
        - name: service-images-nest-rest
          image: rat-or-cat/service-images-nest-rest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: svc-image-service
  namespace: rat-or-cat
spec:
  selector:
    app: service-images-nest-rest
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
