apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: rat-or-cat
spec:
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: rat-or-cat/api-gateway
          ports:
            - containerPort: 8080
          env:
            - name: IMAGE_SERVICE_URI
              value: "http://svc-image-service:3000"
---
apiVersion: v1
kind: Service
metadata:
  name: svc-api-gateway
  namespace: rat-or-cat
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
