apiVersion: apps/v1
kind: Deployment
metadata:
  name: rat-or-cat-image-service
spec:
  selector:
    matchLabels:
      app: image-service
  template:
    metadata:
      labels:
        app: image-service
    spec:
      containers:
        - name: image-service
          image: rat-or-cat/image-service
          ports:
            - containerPort: 3000
